### ISSUE TITLE
[Documentation] Add anchor links

### ISSUE THREAD

**Issue by abhisekp** [abhisekp/Practice-Modern-JavaScript#17]
Add anchor links to all instruction steps in `README.md`

**Comment by lesliekimm** [comment]
this looks like its working??

**Comment by abhisekp** [comment]
@lesliekimm some of the instruction steps i.e. the steps with numbering should also be linkable.

See [**Airbnb JavaScript Style Guide**](https://github.com/airbnb/javascript#airbnb-javascript-style-guide-)
