### ISSUE TITLE
[Extras] Add a chatting technology

### ISSUE THREAD

**Issue by abhisekp** [abhisekp/Practice-Modern-JavaScript#6]
Add a Gitter chat badge to allow for help and support using direct chat.

**Comment by co16353sidak** [comment]
Would like to work on this issue @abhisekp, what is the status of this issue ?

**Comment by abhisekp** [comment]
@co16353sidak Currently, we can use this chatroom [**gitter.im/abhisekp/ComputerEnthusiasts**](https://gitter.im/abhisekp/ComputerEnthusiasts?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

You may add a gitter badge using the given link.

**Comment by co16353sidak** [comment]
Please review @abhisekp
